server:
  port: 8848

spring:
  application:
    name: cloud-consumer-service

  datasource:
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root


eureka:
  client:
    service-url: # eureka的地址信息
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
    fetch-registry: true
    register-with-eureka: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.sgming.springcloud.entity