server:
  port: 8849

spring:
  application:
    name: cloud-consumer-feign-service

  datasource:
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root


eureka:
  client:
    service-url: # eureka的地址信息
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
    register-with-eureka: false

ribbon:
  # 建立连接所用时间，适用于网络状态正常的情况，两端连接所用的时间
  ReadTimeout: 5000
  # 建立连接后从服务器读取可用资源的所用时间
  ConnectTimeout: 5000

logging:
  level:
    cn.sgming.springcloud.service.PaymentOpenFeign: debug